### ISSUE TITLE
[CustomFieldsEntityTrait] Getter that returns all custom fields, also empty ones

### ISSUE THREAD

**Issue by MartinRosserEB** [EmchBerger/cube-custom-fields-bundle#44]
Use Case:

Show a list of entities in a table. Table heading shall match table cell content.

**Comment by SimonHeimberg** [comment]
for the show page, there is getDataAll($entity) in https://github.com/EmchBerger/cube-custom-fields-bundle/blob/master/src/Utils/CustomFieldShowService.php#L34

Index service returns all fields: https://github.com/EmchBerger/cube-custom-fields-bundle/blob/master/src/Utils/CustomFieldIndexService.php

What exactly is missing?

**Comment by MartinRosserEB** [comment]
The use case is applied in Twig. I.e., the Utils will have to be applied in Twig (e.g. through a custom Twig function invoking getDataAll).

What is more, this is applied on an array of objects containing custom fields. Therefore, to extract header information, either the configReader service will have to be usable from Twig as well, or getDataAll will have to be applied twice for an entry of the array.

Array preparation in the controller is feasible, and in that case likely easier.

**Comment by MartinRosserEB** [comment]
This is now solved through array preparation in the controller.
