### ISSUE TITLE
[Migration] Make bundle suitable for application while migrating to no bundle architecture

### ISSUE THREAD

**Issue by krzysztofruszczynski** [EmchBerger/cube-custom-fields-bundle#60]
From Symfony 4, it is recommended that application is not placed in a bundle. If someone is refactoring application, it is possible, that in database are references to application in a bundle. Bridge support old database entries have to be built.

**Comment by SimonHeimberg** [comment]
Problem to solve:
When switching to flex, the entity names change from `AppBundle\Entity\X` to `App\Entity\X`.

When a custom field is linked to a class from the app, it saves the class name in the database. When this is loaded with new directory structure, the class is not found.

To handle this correctly, a doctrine migration must be written.
But at least while developping the migration (but probably longer), there will be cases where the class name do not match. For this case is the suggestion of a "bridge".

Implementation details may be discussed.

**Comment by SimonHeimberg** [comment]
replaced with a `fallback loader`:

```php
spl_autoload_register(function ($className) {
    if ('AppBundle\\' === substr($className, 0, 10)) {
        $newClassName = 'App\\'.substr($className, 10);
        if (class_alias($newClassName, $className)) {
            @trigger_error(sprintf('found old class "%s", use "%s" instead', $className, $newClassName), E_USER_DEPRECATED);
        }
    }
});
```
